/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components (manually enhanced for Element Plus)
// Read more: https://github.com/vuejs/core/pull/3399

export {};

declare module 'vue' {
  export interface GlobalComponents {
    // Layout 布局
    ElContainer: typeof import('element-plus/es')['ElContainer'];
    ElHeader: typeof import('element-plus/es')['ElHeader'];
    ElAside: typeof import('element-plus/es')['ElAside'];
    ElMain: typeof import('element-plus/es')['ElMain'];
    ElFooter: typeof import('element-plus/es')['ElFooter'];

    // Basic 基础
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElLink: typeof import('element-plus/es')['ElLink'];

    // Form 表单
    ElForm: typeof import('element-plus/es')['ElForm'];
    ElFormItem: typeof import('element-plus/es')['ElFormItem'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber'];
    ElSelect: typeof import('element-plus/es')['ElSelect'];
    ElOption: typeof import('element-plus/es')['ElOption'];
    ElCascader: typeof import('element-plus/es')['ElCascader'];
    ElSwitch: typeof import('element-plus/es')['ElSwitch'];
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox'];
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup'];
    ElRadio: typeof import('element-plus/es')['ElRadio'];
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup'];
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton'];
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker'];
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker'];
    ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect'];
    ElUpload: typeof import('element-plus/es')['ElUpload'];
    ElRate: typeof import('element-plus/es')['ElRate'];
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker'];
    ElTransfer: typeof import('element-plus/es')['ElTransfer'];
    ElSlider: typeof import('element-plus/es')['ElSlider'];
    ElAutoComplete: typeof import('element-plus/es')['ElAutoComplete'];

    // Data 数据展示
    ElTable: typeof import('element-plus/es')['ElTable'];
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn'];
    ElTag: typeof import('element-plus/es')['ElTag'];
    ElProgress: typeof import('element-plus/es')['ElProgress'];
    ElTree: typeof import('element-plus/es')['ElTree'];
    ElPagination: typeof import('element-plus/es')['ElPagination'];
    ElBadge: typeof import('element-plus/es')['ElBadge'];
    ElAvatar: typeof import('element-plus/es')['ElAvatar'];
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton'];
    ElEmpty: typeof import('element-plus/es')['ElEmpty'];

    // Notice 反馈
    ElAlert: typeof import('element-plus/es')['ElAlert'];
    ElDialog: typeof import('element-plus/es')['ElDialog'];
    ElDrawer: typeof import('element-plus/es')['ElDrawer'];
    ElPopover: typeof import('element-plus/es')['ElPopover'];
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm'];
    ElTooltip: typeof import('element-plus/es')['ElTooltip'];
    // ElMessageBox / ElMessage / ElNotification 是函数式 API，无需组件注册

    // Navigation 导航
    ElMenu: typeof import('element-plus/es')['ElMenu'];
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
    ElSubmenu: typeof import('element-plus/es')['ElSubmenu'];
    ElTabs: typeof import('element-plus/es')['ElTabs'];
    ElTabPane: typeof import('element-plus/es')['ElTabPane'];
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb'];
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem'];
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader'];
    ElDropdown: typeof import('element-plus/es')['ElDropdown'];
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu'];
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem'];
    ElSteps: typeof import('element-plus/es')['ElSteps'];
    ElStep: typeof import('element-plus/es')['ElStep'];

    // Others 其他
    ElDivider: typeof import('element-plus/es')['ElDivider'];
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar'];
    ElBacktop: typeof import('element-plus/es')['ElBacktop'];

    // Vue Router
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
